server:
  port: 8066
spring:
  datasource:
    url: jdbc:mysql://192.168.113.15:3306/log_platform?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 3nodapp
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 10000
      auto-commit: true
      connection-test-query: SELECT 1
  cache: 
    type: redis
    redis:
      cache-null-values: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB